

DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  
  longitude NVARCHAR(250) NOT NULL,
  latitude NVARCHAR(250) NOT NULL,
  device_type VARCHAR(250) DEFAULT NULL,
  ip_device VARCHAR(250) DEFAULT NULL,
  date_current DATE DEFAULT NULL
  
  
);


